###
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="IMG_3726.JPG"

< C:\Users\shuku\Desktop\IMG_3726.JPG

###
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Muhammad Yusuf ShukurovStrong) Resume.pdf"

< C:\Users\shuku\Desktop\Muhammad Yusuf ShukurovStrong) Resume.pdf

### delete
DELETE http://localhost:8080/api/v1/attach/delete/e325583b-86c1-4f1d-b849-8758f26935b4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDU5MjYwNjgsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJBRE1JTiIsIk1JTl9BRE1JTiJdLCJleHAiOjE3MDY3OTAwNjgsImlzcyI6ImFwcGxpY2FudCBQT1JUQUwifQ.Sz6MtKs2k_a_YkA0XYuMikDSqHodAqVehvenvDr4hc77EuKD83P8Ciy0aqNjbgn09NfHcmG1gePwsBsho0Gpug
