### Create basket
POST localhost:8082/api/v1/basket/create
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODkxNzcsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiTU9ERVJBVE9SIiwiU1VQRVJfQURNSU4iLCJVU0VSIiwiQURNSU4iXSwiZXhwIjoyNjU0MTY5MTc3LCJpc3MiOiJ0aGluayBzdG9yZSJ9.kwoe7LGYgGYWmP3GyO9MWPRv2Ub6Dn6dZ4mlQs3zszqbb-mvGOn3kLy0vjKP9t8aHVN18QTsMkJ7B0JoR_sgVg
Content-Type: application/json

{
  "bookId": "b93d0e45-1701-48f4-8fc4-40577e19d790"
}


### Update basket
PUT localhost:8082/api/v1/basket/buy/b93d0e45-1701-48f4-8fc4-40577e19d790
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODkxNzcsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiTU9ERVJBVE9SIiwiU1VQRVJfQURNSU4iLCJVU0VSIiwiQURNSU4iXSwiZXhwIjoyNjU0MTY5MTc3LCJpc3MiOiJ0aGluayBzdG9yZSJ9.kwoe7LGYgGYWmP3GyO9MWPRv2Ub6Dn6dZ4mlQs3zszqbb-mvGOn3kLy0vjKP9t8aHVN18QTsMkJ7B0JoR_sgVg

###
DELETE localhost:8082/api/v1/basket/delete/dec9626f-2f73-4f1e-904f-f4eb789e44b2
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODY4NzksImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiTU9ERVJBVE9SIiwiQURNSU4iXSwiZXhwIjoyNjU0MTY2ODc5LCJpc3MiOiJ0aGluayBzdG9yZSJ9.NlRxwTW2__Z8vgVmBEu9BsZd4EyjvuexpiA65_VpQ7Ko0hcXmhRqX4C4xJHL5uGF6wDO-gAv8cLvgpJSF3O1Mw

###

GET http://localhost:8082/api/v1/basket/get-basket-books
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODkxNzcsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiTU9ERVJBVE9SIiwiU1VQRVJfQURNSU4iLCJVU0VSIiwiQURNSU4iXSwiZXhwIjoyNjU0MTY5MTc3LCJpc3MiOiJ0aGluayBzdG9yZSJ9.kwoe7LGYgGYWmP3GyO9MWPRv2Ub6Dn6dZ4mlQs3zszqbb-mvGOn3kLy0vjKP9t8aHVN18QTsMkJ7B0JoR_sgVg
###

GET http://localhost:8082/api/v1/basket/get-purchased-books
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODY4NzksImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiTU9ERVJBVE9SIiwiQURNSU4iXSwiZXhwIjoyNjU0MTY2ODc5LCJpc3MiOiJ0aGluayBzdG9yZSJ9.NlRxwTW2__Z8vgVmBEu9BsZd4EyjvuexpiA65_VpQ7Ko0hcXmhRqX4C4xJHL5uGF6wDO-gAv8cLvgpJSF3O1Mw
###Get basket
GET localhost:8082/api/v1/basket/open/get-all

### Get By Id
GET http://localhost:8082/api/v1/basket/open/get-by-id/88759f49-49aa-45a7-bae9-9f76f0f0bfd4

###
GET http://localhost:8082/api/v1/basket/open/get-all-by-category-id/dec9626f-2f73-4f1e-904f-f4eb789e44b2


