### Create basket
POST localhost:8080/api/v1/basket/create
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODkxNzcsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiTU9ERVJBVE9SIiwiU1VQRVJfQURNSU4iLCJVU0VSIiwiQURNSU4iXSwiZXhwIjoyNjU0MTY5MTc3LCJpc3MiOiJ0aGluayBzdG9yZSJ9.kwoe7LGYgGYWmP3GyO9MWPRv2Ub6Dn6dZ4mlQs3zszqbb-mvGOn3kLy0vjKP9t8aHVN18QTsMkJ7B0JoR_sgVg
Content-Type: application/json

{
  "bookId": "1103ed1f-a2f1-4525-a21b-168b7a92d68b"
}


### Update basket
PUT localhost:8080/api/v1/basket/buy/863cf24f-8779-49c8-ae26-64e2e508e195
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwOTY0MTAsImlkIjoiYWZhNDllMjUtNjM3Ny00NGMwLWFiYTMtZWZkZDE3Nzc3OGNkIiwicm9sZXMiOlsiVVNFUiJdLCJleHAiOjI2NTQxNzY0MTAsImlzcyI6InRoaW5rIHN0b3JlIn0.bqVn7ssyBGCZ1mLYvWTW3OJSRUWiLRqVVOWzVZv2mGQjbAbIik-Bt2xMsrNSL8DAkmz5mNiZpa8oFeQP-vF8gw

###
DELETE localhost:8080/api/v1/basket/delete/dec9626f-2f73-4f1e-904f-f4eb789e44b2
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODY4NzksImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiTU9ERVJBVE9SIiwiQURNSU4iXSwiZXhwIjoyNjU0MTY2ODc5LCJpc3MiOiJ0aGluayBzdG9yZSJ9.NlRxwTW2__Z8vgVmBEu9BsZd4EyjvuexpiA65_VpQ7Ko0hcXmhRqX4C4xJHL5uGF6wDO-gAv8cLvgpJSF3O1Mw

###

GET http://localhost:8080/api/v1/basket/get-basket-books
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwOTY0MTAsImlkIjoiYWZhNDllMjUtNjM3Ny00NGMwLWFiYTMtZWZkZDE3Nzc3OGNkIiwicm9sZXMiOlsiVVNFUiJdLCJleHAiOjI2NTQxNzY0MTAsImlzcyI6InRoaW5rIHN0b3JlIn0.bqVn7ssyBGCZ1mLYvWTW3OJSRUWiLRqVVOWzVZv2mGQjbAbIik-Bt2xMsrNSL8DAkmz5mNiZpa8oFeQP-vF8gw

###

GET http://localhost:8080/api/v1/basket/get-purchased-books
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwOTY0MTAsImlkIjoiYWZhNDllMjUtNjM3Ny00NGMwLWFiYTMtZWZkZDE3Nzc3OGNkIiwicm9sZXMiOlsiVVNFUiJdLCJleHAiOjI2NTQxNzY0MTAsImlzcyI6InRoaW5rIHN0b3JlIn0.bqVn7ssyBGCZ1mLYvWTW3OJSRUWiLRqVVOWzVZv2mGQjbAbIik-Bt2xMsrNSL8DAkmz5mNiZpa8oFeQP-vF8gw

##DIYORBEK
### Create basket
POST localhost:8080/api/v1/basket/create
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwOTY5OTEsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiVVNFUiIsIlNVUEVSX0FETUlOIiwiQURNSU4iLCJNT0RFUkFUT1IiXSwiZXhwIjoyNjU0MTc2OTkxLCJpc3MiOiJ0aGluayBzdG9yZSJ9.19Ue2NA0hfVfGM_bFdtvWOC8gub5hVLQ60hsVuA0cJhxygp_yQ9lUz3bUsdWcg61MaekqUJsEg65i_qbBs9GgQ
Content-Type: application/json

{
  "bookId": "ccd3584c-3fbc-43fe-8535-066bb6ebd8e2"
}


### Update basket
PUT localhost:8080/api/v1/basket/buy/863cf24f-8779-49c8-ae26-64e2e508e195
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwOTY5OTEsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiVVNFUiIsIlNVUEVSX0FETUlOIiwiQURNSU4iLCJNT0RFUkFUT1IiXSwiZXhwIjoyNjU0MTc2OTkxLCJpc3MiOiJ0aGluayBzdG9yZSJ9.19Ue2NA0hfVfGM_bFdtvWOC8gub5hVLQ60hsVuA0cJhxygp_yQ9lUz3bUsdWcg61MaekqUJsEg65i_qbBs9GgQ

###
DELETE localhost:8080/api/v1/basket/delete/dec9626f-2f73-4f1e-904f-f4eb789e44b2
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODY4NzksImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIiwiTU9ERVJBVE9SIiwiQURNSU4iXSwiZXhwIjoyNjU0MTY2ODc5LCJpc3MiOiJ0aGluayBzdG9yZSJ9.NlRxwTW2__Z8vgVmBEu9BsZd4EyjvuexpiA65_VpQ7Ko0hcXmhRqX4C4xJHL5uGF6wDO-gAv8cLvgpJSF3O1Mw

###

GET http://localhost:8080/api/v1/basket/get-basket-books
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwOTY5OTEsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiVVNFUiIsIlNVUEVSX0FETUlOIiwiQURNSU4iLCJNT0RFUkFUT1IiXSwiZXhwIjoyNjU0MTc2OTkxLCJpc3MiOiJ0aGluayBzdG9yZSJ9.19Ue2NA0hfVfGM_bFdtvWOC8gub5hVLQ60hsVuA0cJhxygp_yQ9lUz3bUsdWcg61MaekqUJsEg65i_qbBs9GgQ

###

GET http://localhost:8080/api/v1/basket/get-purchased-books
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwOTY5OTEsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiVVNFUiIsIlNVUEVSX0FETUlOIiwiQURNSU4iLCJNT0RFUkFUT1IiXSwiZXhwIjoyNjU0MTc2OTkxLCJpc3MiOiJ0aGluayBzdG9yZSJ9.19Ue2NA0hfVfGM_bFdtvWOC8gub5hVLQ60hsVuA0cJhxygp_yQ9lUz3bUsdWcg61MaekqUJsEg65i_qbBs9GgQ



###Get basket
GET localhost:8080/api/v1/basket/open/get-all

### Get By Id
GET http://localhost:8080/api/v1/basket/open/get-by-id/88759f49-49aa-45a7-bae9-9f76f0f0bfd4

###
GET http://localhost:8080/api/v1/basket/open/get-all-by-category-id/dec9626f-2f73-4f1e-904f-f4eb789e44b2


