### Create book
POST localhost:8082/api/v1/book/create
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODkxNzcsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiTU9ERVJBVE9SIiwiU1VQRVJfQURNSU4iLCJVU0VSIiwiQURNSU4iXSwiZXhwIjoyNjU0MTY5MTc3LCJpc3MiOiJ0aGluayBzdG9yZSJ9.kwoe7LGYgGYWmP3GyO9MWPRv2Ub6Dn6dZ4mlQs3zszqbb-mvGOn3kLy0vjKP9t8aHVN18QTsMkJ7B0JoR_sgVg
Content-Type: application/json

{
  "title": "Katta",
  "author": "Katta",
  "description": "Katta",
  "price": "6600",
  "categoryId": "fb6402c7-9b1b-4885-beb7-09ffb2910072",
  "photoId": "f9cae48f-396e-41bb-ab3f-64a5df32b5ff",
  "pdfId": "79b0769b-0e56-4794-a16d-f32909d6e1d9"
}


### Update book
PUT localhost:8082/api/v1/book/update/88759f49-49aa-45a7-bae9-9f76f0f0bfd4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcwODA4NDgsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiVVNFUiIsIlNVUFBMSUVSIiwiTU9ERVJBVE9SIiwiU1VQRVJfQURNSU4iLCJBRE1JTiJdLCJleHAiOjE3MDc5NDQ4NDgsImlzcyI6InRoaW5rIHN0b3JlIn0.lfe5MAFj4vSSCdFjprEoKM0a2zvZvYfHlfBgR_T83nwSxphElv8wgjDYZjHkqU1fg4y3B4Yr7K3EgyzczrDpDA
Content-Type: application/json

{
  "title": "Erkak",
  "author": "Erkak",
  "description": "Erkak"
}

###
DELETE localhost:8082/api/v1/book/delete/dec9626f-2f73-4f1e-904f-f4eb789e44b2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcwODA4NDgsImlkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwicm9sZXMiOlsiVVNFUiIsIlNVUFBMSUVSIiwiTU9ERVJBVE9SIiwiU1VQRVJfQURNSU4iLCJBRE1JTiJdLCJleHAiOjE3MDc5NDQ4NDgsImlzcyI6InRoaW5rIHN0b3JlIn0.lfe5MAFj4vSSCdFjprEoKM0a2zvZvYfHlfBgR_T83nwSxphElv8wgjDYZjHkqU1fg4y3B4Yr7K3EgyzczrDpDA

###Get book
GET localhost:8082/api/v1/book/open/get-all

### Get By Id
GET http://localhost:8082/api/v1/book/open/get-by-id/88759f49-49aa-45a7-bae9-9f76f0f0bfd4


###
GET http://localhost:8082/api/v1/book/open/get-all-by-category-id/dec9626f-2f73-4f1e-904f-f4eb789e44b2


